### ISSUE TITLE
Provide ability to bypass custom field definition retrieval with New-VenafiSession

### ISSUE THREAD

**Issue by gdbarron** [Venafi/VenafiPS#122]
# Summary of the new feature/enhancement

New-VenafiSession will retrieve custom field definitions for assistance with attribute get/set functions.  When list type custom fields have a large number of values, retrieval can take quite a while and delay session creation.  Provide the ability to bypass this retrieval.  

# Proposed technical implementation details (optional)

**Comment by gdbarron** [comment]
@Saadi6 FYI

**Comment by Saadi6** [comment]
The delay is only noticeable when creating a new session from PS Core on a Mac. On Windows it is not noticeable but can be measured (takes approx. 190ms longer with 1.5k AllowedValues in Custom Fields). 

TPP's REST does not provide a method to only fetch Custom Field GUIDs and labels. The method (Metadata/GetItemsForClass) currently used by Get-TppCustomField.ps1 is indeed most appropriate for the purpose. Since  custom fields information stored in VenafiSession object is used by various functions in VenafiPS, it would be difficult to make this optional without sacrificing functionality.

I don't imagine many installations have large amount of data in AllowedValues so this could be an edge case. Unless there is a way in PowerShell to instantiate these properties when they are first used (through delegates and reflection...?), this can be closed.

**Comment by gdbarron** [comment]
From our conversation, it sounded like this was more of an issue.  I'll close this without updates.
