### ISSUE TITLE
set-attribute

### ISSUE THREAD

**Issue by tonyjameshart** [Venafi/VenafiPS#172]
# Environment

```
Operating System: Windows 10
VenafiPS version: 4.4.0
PowerShell version: 5.1.19041.1682 
TPP version (if applicable): 22.3.1
```
# Steps to reproduce
Get-Tppobject -Path $app.Path | Get-TppAttribute -Attribute 'Certificate'  #shows value
Set-TppAttribute -Path $app.Path -Attribute @{'Certificate'= $null} #removes association
Get-Tppobject -Path $app.Path | Get-TppAttribute -Attribute 'Certificate'  #shows attribute Certificate value as {}

# Expected behavior
To have the previously associated certificate show no association to the $app

# Actual behavior
$app shows no association when the $app.Certificate.Value attribute is set to $null
The 'previously' associated cert still shows an association with the $app in Aperture when looking at the cert.
 
# Screenshots
![set-tppattribute 1](https://user-images.githubusercontent.com/5884587/204924476-eb433eba-5432-4b75-a2eb-a4184fe54291.PNG)
![image](https://user-images.githubusercontent.com/5884587/204924591-23d1246f-e3b8-4447-b2a2-e727a2d6a94f.png)

**Comment by wilddev65** [comment]
This is expected behavior. As you did not use `Remove-TppCertificateAssociation` as Greg mentioned, you are not using the proper underlying way that TPP removes associations.

In TPP, when a certificate object is associated with an app there are two attributes involved. One on the certificate called `Consumer` and one on the app called `Certificate`. You have only removed one side of this by setting the app to $null.

Closing this as it is the proper behavior for this function.
